### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Imprimtive** [adrian-soch/frontier_exploration#6]
I did not found that exploration.launch.py in launch files but there is classical_exploration.launch.py,  and when I run ros2 launch with it said that package 'turtlebot4_ignition_bringup' not found with the order os2 launch frontier_exploration turtlebot_full_stack.launch.py.
![Uploading error.png…]()

**Comment by adrian-soch** [comment]
You will need to install the Turtlebot 4 packages and Ignition Gazebo.
